version: "3.9"

# Services
services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.10
    # Enables the web UI and tells Traefik to listen to docker
    command: --configFile=/etc/traefik/traefik.yml
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml

  ticket-service:
    build: ./ticket-service
    volumes:
      - ./ticket-service:/home/bun/app
    labels:
      - "traefik.http.routers.ticket-service.rule=Host(`api.ticket-service.localhost`)"
    hostname: api.ticket-service.docker-compose
